# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: "%env(APP_SECRET)%"
  #csrf_protection: true

  # Note that the session will be started ONLY if you read or write from it.
  session:
    enabled: true
    handler_id: session.handler.native_file
    save_path: "%kernel.project_dir%/var/sessions/%kernel.environment%"
    cookie_lifetime: 0
    cookie_secure: "auto"
    cookie_samesite: "lax"
    cookie_httponly: true
    gc_maxlifetime: 3600
    storage_factory_id: session.storage.factory.native

  #esi: true
  #fragments: true

  php_errors:
    log: true
    throw: false

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file

when@dev:
  framework:
    profiler: true
